build:
 image: openjdk:8-jdk
 script:
   - apt-get update
   - apt-get -y install graphviz
   - ./gradlew asciidoctorRevealJs
 stage: build
 artifacts:
  paths:
  - build/docs

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public
    - cp -R build/docs/asciidocRevealJs/* public/
  artifacts:
    paths:
    - public
  when: manual

