before_script:
  - apt-get update
  - apt-get -y install graphviz

build:
 image: openjdk:8-jdk
 script:
 - ./gradlew build
 stage: build
 artifacts:
  paths:
  - build/docs

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public
    - cp -R build/docs/slides/* public/
  artifacts:
    paths:
    - public
  when: manual

