before_script:
  - apt-get update
  - apt-get -y install graphviz

build:
 image: java:8
 script:
 - ./gradlew build
 stage: build
 artifacts:
  paths:
  - build/asciidoc

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public
    - cp -R build/asciidoc/revealjs/* public/
  artifacts:
    paths:
    - public
  when: manual

