= Presentation Template: Cuando el tiempo apremia
Jorge Aguilera <jorge.aguilera@puravida-software.com>
2018-09-01
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]

== Presentation template

* Plantilla para descargar y empezar a escribir una presentación html
* Olvidate de PowerPoint
* Añade diagramas y/o fórmulas LaTex
* Sólo necesitas Java (y si usas Gitlab o Github ni eso)

== Instrucciones (flecha abajo)

=== Descargar

* Descargar desde https://gitlab.com/jorge-aguilera/presentation-template/-/archive/master/presentation-template-master.zip
* Descomprimir 

=== Editar

* Abrir el fichero src/main/asciidoc/index.adoc
* Es un fichero de texto. Puedes editarlo hasta con notepad
* Echa un ojo a https://asciidoctor.org/docs/asciidoctor-revealjs/#syntax-examples para ver lo que puedes hacer


=== Generar

* Ejecutar `./gradlew asciidoctor`

=== Nada más

* Tu presentación lista en `build/asciidoc/revealjs/index.html`

== Ejemplo

A continuación algunas transparencias de ejemplo

== Presentación

[%step]
* Quién soy
* Qué hago.
* Porqué lo hago.

== Agenda

[%step]
* Punto 1
* Punto 2
* Punto 3

== Notas

Puedes usar notas que solo veas tú:

[source]
----
[NOTE.speaker]
--
Aqui deberia hablar de mi libro.
(pulsa s y deberias ver una ventana nueva)
--
----

[NOTE.speaker]
--
Aqui deberia hablar de mi libro.
--

== Diagramas

[plantuml, diagram-class, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

== Formulas

[plantuml,formulas,png]
....

:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note

....

[transition=zoom, %notitle]
== Transiciones

No abuses de las transiciones y tendrás ganada a la audiencia

[transition-speed=fast, %notitle]
== Speed

Aunque una transición rapidita no está mal


