== Ejemplo

A continuación algunas transparencias de ejemplo

== Presentación

[%step]
* Quién soy
* Qué hago.
* Porqué lo hago.

== Agenda

[%step]
* Punto 1
* Punto 2
* Punto 3

== Notas

Puedes usar notas que solo veas tú:

[source]
----
[NOTE.speaker]
--
Aqui deberia hablar de mi libro.
(pulsa s y deberias ver una ventana nueva)
--
----

[NOTE.speaker]
--
Aqui deberia hablar de mi libro.
--

== Charts

++++
<canvas data-chart="line">
Month, January, February, March, April, May, June, July
My first dataset, 65, 59, 80, 81, 56, 55, 40
My second dataset, 28, 48, 40, 19, 86, 27, 90
</canvas>
++++

== Código

Puedes escribir código resaltado con colores:

[source,groovy]
----
(0..10).each{
    println "$it.- ${new Date()}"
}
----

== Diagramas

Puedes escribir bloques usando sintáxis PlantUML

[source]
----
[plantuml, diagram-class, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....
----

=== Diagram

.Y obtienes este diagrama
[plantuml, diagram-class, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....


== Formulas

Puedes escribir fórmulas dentro de los diagramas. Por ejemplo:

[source]
----
[plantuml,formulas,png]
....
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note
....
----

=== Formulas

Obtienes esto

[plantuml,formulas,png]
....
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note
....

[transition=zoom, %notitle]
== Transiciones

No abuses de las transiciones y tendrás ganada a la audiencia

[transition-speed=fast, %notitle]
== Speed

Aunque una transición rapidita no está mal


== QRCode

¿Quieres añadir un código a una URL para que tu audiencia pueda
capturarlo con el móvil?

barcode::qrcode[https://jorge-aguilera.gitlab.io/presentation-template/#/,300,300]

(PuraVida Software asciidoctor extension)

